# Generated by Django 2.2.4 on 2019-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0003_auto_20190916_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='content',
            field=models.TextField(default='', verbose_name='动态内容'),
        ),
    ]
