# Generated by Django 2.2.4 on 2019-09-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0004_auto_20190926_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserBackgroundImage', models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='个人动态的图片')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend.Trend')),
            ],
            options={
                'verbose_name': '个人动态图片',
                'verbose_name_plural': '个人动态图片',
            },
        ),
    ]
