# Generated by Django 2.2.4 on 2019-09-26 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trend', '0005_trendphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendcomment',
            name='layer',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trendcomment',
            name='touser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trendcommentto', to=settings.AUTH_USER_MODEL, verbose_name='给谁回复'),
        ),
        migrations.AlterField(
            model_name='trendcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trendsub_comm', to='trend.TrendComment'),
        ),
        migrations.AlterField(
            model_name='trendcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trendcommentfrom', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
