# Generated by Django 2.2.4 on 2019-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0007_auto_20190926_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendphoto',
            name='UserBackgroundImage',
        ),
        migrations.AddField(
            model_name='trendclass',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='trend/', verbose_name='动态分类图'),
        ),
        migrations.AddField(
            model_name='trendphoto',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='trend/', verbose_name='个人动态的图片'),
        ),
    ]
