# Generated by Django 2.2.4 on 2019-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0012_auto_20190927_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendclass',
            name='desc',
            field=models.TextField(default='', verbose_name='动态类别描述'),
        ),
    ]
