# Generated by Django 2.2.4 on 2019-09-28 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trend', '0015_auto_20190928_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendupdown',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='trendupdown',
            unique_together={('user', 'article')},
        ),
    ]
