# Generated by Django 2.2.4 on 2019-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0016_auto_20190928_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
        migrations.AlterField(
            model_name='trendclass',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
