# Generated by Django 2.2.4 on 2019-08-21 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_disabled', models.BooleanField(default=True, verbose_name='是否私密')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '博客社区轮播图',
                'verbose_name_plural': '博客社区轮播图',
            },
        ),
        migrations.CreateModel(
            name='OjCarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_disabled', models.BooleanField(default=True, verbose_name='是否私密')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement/', verbose_name='图片')),
            ],
            options={
                'verbose_name': 'OJ轮播图',
                'verbose_name_plural': 'OJ轮播图',
            },
        ),
        migrations.AlterField(
            model_name='announcement',
            name='Belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公告标题'),
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
    ]
