# Generated by Django 2.2.4 on 2019-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_auto_20190821_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
        migrations.AlterField(
            model_name='blogcarouselimg',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
        migrations.AlterField(
            model_name='ojcarouselimg',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
    ]
