# Generated by Django 2.2.4 on 2019-10-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20191008_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='blogcarouselimg',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='ojcarouselimg',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否可用'),
        ),
    ]
