# Generated by Django 2.2.4 on 2019-10-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingcontest',
            name='problem_list',
        ),
    ]
