# Generated by Django 2.2.4 on 2019-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_codingcontest_problem_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingcontest',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
