# Generated by Django 2.2.4 on 2019-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
        migrations.AlterField(
            model_name='userinfoimg',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
    ]
