# Generated by Django 2.2.4 on 2019-09-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190912_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
        migrations.AlterField(
            model_name='user',
            name='FavouriteWriters',
            field=models.TextField(blank=True, default='...', max_length=1024, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
        migrations.AlterField(
            model_name='userinfoimg',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否展示'),
        ),
    ]
