# Generated by Django 2.2.4 on 2019-09-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190916_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='FavouriteWriters',
        ),
        migrations.AddField(
            model_name='user',
            name='NickName',
            field=models.TextField(blank=True, default='...', max_length=256, null=True, verbose_name='昵称'),
        ),
    ]
