# Generated by Django 2.2.4 on 2019-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190916_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='NickName',
            field=models.TextField(blank=True, default='该用户没有设置昵称', max_length=256, null=True, verbose_name='昵称'),
        ),
    ]
