# Generated by Django 2.2.4 on 2019-09-27 10:06

from django.db import migrations, models
import utils.SomeSetting


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190916_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoimg',
            name='UserAvatar',
            field=models.ImageField(blank=True, default='user/defaultavatar.jpg', null=True, storage=utils.SomeSetting.LiterDocStorage(), upload_to='user/', verbose_name='头像'),
        ),
    ]
