# Generated by Django 2.2.4 on 2019-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190908_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
    ]
