# Generated by Django 2.2.4 on 2019-08-21 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.IntegerField(db_index=True, default=6, verbose_name='评测状态')),
                ('use_time', models.IntegerField(default=0, verbose_name='耗时 （ms）')),
                ('use_memory', models.IntegerField(default=0, verbose_name='耗空（mb）')),
                ('info', models.TextField(verbose_name='判题器返回信息')),
                ('language', models.TextField(verbose_name='选择的语言')),
                ('ip', models.CharField(max_length=50, verbose_name='该次提交时的IP地址')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.CodingContest', verbose_name='哪场比赛')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.CodingProlemInfo', verbose_name='对应问题')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='哪个人交的')),
            ],
            options={
                'verbose_name': '提交',
                'verbose_name_plural': '提交',
                'db_table': '提交表',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='SourceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='提交的源代码')),
                ('Sumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.CodingSubmission', verbose_name='提交ID')),
            ],
            options={
                'verbose_name': '源代码',
                'verbose_name_plural': '源代码',
                'db_table': '源代码表',
            },
        ),
    ]
