# Generated by Django 2.2.4 on 2019-09-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemabstract',
            name='degree',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'Hard')], default=2, verbose_name='题目难度'),
        ),
    ]
