# Generated by Django 2.2.4 on 2019-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problemabstract_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtages',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否为热门题型'),
        ),
        migrations.AlterField(
            model_name='problemabstract',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
        migrations.AlterField(
            model_name='problemtages',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否私密(有效)'),
        ),
    ]
