# Generated by Django 2.2.4 on 2019-09-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20190913_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingproleminfo',
            options={'ordering': ['create_time'], 'verbose_name': '编程问题', 'verbose_name_plural': '编程问题'},
        ),
        migrations.AlterField(
            model_name='problemabstract',
            name='source',
            field=models.CharField(blank=True, default='原创', max_length=100, null=True, verbose_name='来源'),
        ),
    ]
