# Generated by Django 2.2.4 on 2019-10-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20191008_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemabstract',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='belongcontent', to='contest.CodingContest'),
        ),
    ]
