# Generated by Django 2.2.4 on 2019-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20191010_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemabstract',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否不可用'),
        ),
        migrations.AlterField(
            model_name='problemtages',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否不可用'),
        ),
    ]
