# Generated by Django 2.2.4 on 2019-09-07 14:22

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否私密')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='摘要')),
                ('State', models.IntegerField(choices=[(1, '审核通过'), (2, '审核中'), (3, '审核不通过')], default=1, null=True, verbose_name='审核状态')),
                ('browse', models.IntegerField(default=0, verbose_name='浏览量')),
                ('ThumbsUp', models.IntegerField(default=0, verbose_name='点赞量')),
                ('CommentCount', models.IntegerField(default=0, verbose_name='评论数')),
                ('tags', models.ManyToManyField(to='user.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '技术文章',
                'verbose_name_plural': '技术文章',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('layer', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comm', to='article.Comment')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentto', to=settings.AUTH_USER_MODEL, verbose_name='给谁回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentfrom', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='ArticleUpDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
