# Generated by Django 2.2.4 on 2019-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190916_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
