# Generated by Django 2.2.4 on 2019-09-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='照片')),
            ],
            options={
                'verbose_name': '用户照片',
                'verbose_name_plural': '用户照片',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否私密')),
                ('Desc', models.TextField(max_length=1024, verbose_name='相册描述')),
            ],
            options={
                'verbose_name': '用户相册',
                'verbose_name_plural': '用户相册',
            },
        ),
    ]
