# Generated by Django 2.2.4 on 2019-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20190903_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodetail',
            name='Img',
            field=models.ImageField(upload_to='photo/', verbose_name='照片'),
        ),
    ]
