# Generated by Django 2.2.4 on 2019-09-29 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20190929_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodetail',
            name='Belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='photo.Photos'),
        ),
    ]
