# Generated by Django 2.2.4 on 2019-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_auto_20190929_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
